data_root: '/datasets/nuScenes/Fulldatasetv1.0'
classes: ['car', 'pedestrian', 'bicycle'] # 'motorcycle', 'bus', 'truck']
cams_keys: ['CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_FRONT_LEFT', 'CAM_BACK', 'CAM_BACK_LEFT', 'CAM_BACK_RIGHT']
default_cam: 'CAM_FRONT'
pc_color_param: None
box_color_param:
  min_points_list: [0, 5, 100, 100000]
pc_filter_param:
  limit_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
box_filter_param:
  limit_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
  min_points: 5